# Generated by Django 5.0.5 on 2024-06-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarAccident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("latitude", models.DecimalField(decimal_places=5, max_digits=8)),
                ("longitude", models.DecimalField(decimal_places=5, max_digits=8)),
                ("fatality", models.IntegerField()),
                ("injury", models.IntegerField()),
                ("area_1", models.TextField(max_length=10)),
                ("area_2", models.TextField(max_length=10)),
            ],
            options={
                "db_table": "risk_car_accident",
            },
        ),
        migrations.CreateModel(
            name="CarAccidentDensity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=5, max_digits=8)),
                ("longitude", models.DecimalField(decimal_places=5, max_digits=8)),
                ("total_fatality", models.IntegerField()),
                ("total_injury", models.IntegerField()),
            ],
            options={
                "db_table": "risk_car_accident_density",
            },
        ),
        migrations.CreateModel(
            name="Earthquake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("latitude", models.DecimalField(decimal_places=5, max_digits=8)),
                ("longitude", models.DecimalField(decimal_places=5, max_digits=8)),
                ("magnitude", models.DecimalField(decimal_places=2, max_digits=5)),
                ("depth", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "db_table": "risk_earthquake",
            },
        ),
        migrations.CreateModel(
            name="EarthquakeIntensity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.TextField(max_length=5)),
                ("number", models.IntegerField()),
                ("intensity", models.TextField(max_length=3)),
                ("pgv_lower", models.DecimalField(decimal_places=5, max_digits=8)),
            ],
            options={
                "db_table": "risk_earthquake_intensity",
            },
        ),
        migrations.CreateModel(
            name="PedestrianHell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_1", models.TextField(max_length=5)),
                ("area_2", models.TextField(max_length=10)),
                ("number", models.IntegerField()),
                ("total_fatality", models.IntegerField()),
                ("total_injury", models.IntegerField()),
                ("pedestrian_fatality", models.IntegerField()),
                ("pedestrian_injury", models.IntegerField()),
            ],
            options={
                "db_table": "risk_pedestrian_hell",
            },
        ),
        migrations.CreateModel(
            name="TrafficAccident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("number", models.IntegerField()),
                ("total_fatality", models.IntegerField()),
                ("total_injury", models.IntegerField()),
                ("pedestrian_fatality", models.IntegerField()),
                ("pedestrian_injury", models.IntegerField()),
            ],
            options={
                "db_table": "risk_traffic_accident",
            },
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("fullname", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("verification_code", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "user_info",
            },
        ),
    ]
