# Generated by Django 5.0.5 on 2024-06-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("explorer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotspot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=30)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("area_1", models.TextField(max_length=5)),
                ("area_2", models.TextField(max_length=5)),
                ("address", models.TextField(max_length=50)),
                ("image", models.TextField(max_length=100)),
            ],
            options={
                "db_table": "map_hotspot",
            },
        ),
    ]
