# Generated by Django 5.0.5 on 2024-06-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("explorer", "0002_hotspot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=30)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("area_1", models.TextField(max_length=5)),
                ("area_2", models.TextField(blank=True, max_length=5, null=True)),
                ("address", models.TextField(max_length=50)),
                ("phone", models.TextField(blank=True, max_length=15, null=True)),
                ("opening_hours", models.TextField(max_length=200)),
                ("rating", models.DecimalField(decimal_places=2, max_digits=5)),
                ("avg_price", models.IntegerField()),
                ("image", models.TextField(max_length=100)),
            ],
            options={
                "db_table": "map_restaurant",
            },
        ),
    ]
