# Generated by Django 5.0.5 on 2024-05-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0003_alter_caraccident_table_alter_density_table_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="caraccident",
            old_name="injure",
            new_name="injury",
        ),
    ]
