# Generated by Django 5.0.5 on 2024-05-27 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("explorer", "0004_rename_injure_caraccident_injury"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Density",
            new_name="CarAccidentDensity",
        ),
        migrations.RenameField(
            model_name="caraccidentdensity",
            old_name="latitude_range",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="caraccidentdensity",
            old_name="longitude_range",
            new_name="longitude",
        ),
    ]
