# Generated by Django 5.0.5 on 2024-05-28 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("explorer", "0005_rename_density_caraccidentdensity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="caraccidentdensity",
            old_name="total_injure",
            new_name="total_injury",
        ),
    ]
