# Generated by Django 5.0.5 on 2024-06-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("explorer", "0007_pedestrianhell_trafficaccidents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficaccidents",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name="trafficaccidents",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
