# Generated by Django 5.0.5 on 2024-06-03 01:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("explorer", "0008_alter_trafficaccidents_latitude_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TrafficAccidents",
            new_name="TrafficAccident",
        ),
        migrations.AlterModelTable(
            name="trafficaccident",
            table="risk_traffic_accident",
        ),
    ]
