# Generated by Django 5.0.5 on 2024-06-03 04:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("explorer", "0009_rename_trafficaccidents_trafficaccident_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trafficaccident",
            old_name="fatality",
            new_name="total_fatality",
        ),
        migrations.RenameField(
            model_name="trafficaccident",
            old_name="injury",
            new_name="total_injury",
        ),
    ]
