# Generated by Django 5.0.5 on 2024-06-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("explorer", "0010_rename_fatality_trafficaccident_total_fatality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trafficaccident",
            name="pedestrian_fatality",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trafficaccident",
            name="pedestrian_injury",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
