# Generated by Django 4.2.12 on 2024-05-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('scale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('city', models.TextField(max_length=100)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
