# Generated by Django 5.0.5 on 2024-05-25 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarAccident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("latitude", models.DecimalField(decimal_places=5, max_digits=8)),
                ("longitude", models.DecimalField(decimal_places=5, max_digits=8)),
                ("fatality", models.IntegerField()),
                ("injure", models.IntegerField()),
                ("administrative_area_level_1", models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="CarAccidentDensity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude_range", models.DecimalField(decimal_places=5, max_digits=8)),
                (
                    "longitude_range",
                    models.DecimalField(decimal_places=5, max_digits=8),
                ),
                ("total_fatality", models.IntegerField()),
                ("total_injure", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Earthquake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("latitude", models.DecimalField(decimal_places=5, max_digits=8)),
                ("longitude", models.DecimalField(decimal_places=5, max_digits=8)),
                ("magnitude", models.DecimalField(decimal_places=2, max_digits=5)),
                ("depth", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="EarthquakeIntensity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intensity", models.TextField(max_length=3)),
                ("administrative_area_level_1", models.TextField(max_length=10)),
                (
                    "earthquake",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="map.earthquake",
                    ),
                ),
            ],
        ),
    ]
