# Generated by Django 4.2.12 on 2024-05-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentDensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude_range', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude_range', models.DecimalField(decimal_places=5, max_digits=8)),
                ('fatality', models.IntegerField()),
                ('injure', models.IntegerField()),
            ],
        ),
    ]
